openapi: 3.0.3
info:
  title: Tessell APIs activity-center fsx-netapp-service-controller API
  contact:
    email: support@tessell.com
    name: Tessell Inc
    url: https://www.tessell.com
  description: Tessell API Documentation
  termsOfService: https://www.tessell.com/terms
  version: '1.0'
servers:
- url: '{server}'
  variables:
    server:
      default: console.tessell.com
tags:
- name: fsx-netapp-service-controller
paths:
  /storages/fsx-netapp:
    get:
      tags:
      - fsx-netapp-service-controller
      summary: Get FSx NetApp(s) available for Provisioning DB services
      operationId: getFsxNetAppsConsumerResponse
      parameters:
      - $ref: '#/components/parameters/subscription-query'
      - $ref: '#/components/parameters/region-query'
      - $ref: '#/components/parameters/fsx-statuses'
      - $ref: '#/components/parameters/fsx-skip-statuses'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/pageOffset'
      - name: Authorization
        in: header
        description: Authorization Token
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FsxNetAppConsumerResponse'
        default:
          description: API error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  schemas:
    ApiError:
      type: object
      description: Common error response object for non 2xx responses
      properties:
        code:
          type: string
          description: Status code for the error response
        message:
          type: string
          description: Error message for API response
        resolution:
          type: string
        timestamp:
          type: string
          format: date-time
        contextId:
          type: string
          description: ContextId of API request
        sessionId:
          type: string
          description: SessionId of API request
        tessellErrorCode:
          type: string
          description: Unique error code specific to Tessell
    FsxNetAppSvmStatus:
      enum:
      - AVAILABLE
      - DOWN
      - DELETING
    FsxNetAppConsumerResponse:
      allOf:
      - $ref: '#/components/schemas/apiResponse'
      type: object
      properties:
        response:
          type: array
          items:
            $ref: '#/components/schemas/FsxNetAppConsumerDTO'
    FsxNetAppConfigurationInfo:
      type: object
      description: This is the configuration of FSx NetApp File System
      allOf:
      - $ref: '#/components/schemas/FsxNetAppConfigurationInfoOps'
      properties:
        availableStorage:
          type: integer
          description: Available storage in bytes
          format: int64
          minimum: 0
          default: 0
    apiResponse:
      example:
        metadata:
          pagination:
            pageOffset: 0
            pageSize: 6
          records: 1
          timeZone: timeZone
        response: '{}'
      properties:
        metadata:
          $ref: '#/components/schemas/apiMetadata'
        response:
          type: object
      title: ApiResponse
      type: object
    apiPaginationInfo:
      title: apiPaginationInfo
      type: object
      properties:
        pageSize:
          type: integer
          format: int32
        pageOffset:
          type: integer
          format: int32
    FsxNetAppConnectivityInfo:
      type: object
      description: This is a definition for Tessell FSx-NetApp connectivity
      properties:
        endpoints:
          description: FSx NetApp endpoints
          type: object
          properties:
            interCluster:
              $ref: '#/components/schemas/FsxNetAppEndpointInfo'
            management:
              $ref: '#/components/schemas/FsxNetAppEndpointInfo'
        secretId:
          type: string
          format: uuid
          description: Secret id
        subnets:
          description: FSx NetApp subnets
          type: object
          properties:
            preferred:
              $ref: '#/components/schemas/FsxNetAppSubnetInfo'
            standby:
              $ref: '#/components/schemas/FsxNetAppSubnetInfo'
    FsxNetAppStatus:
      enum:
      - AVAILABLE
      - DOWN
      - DELETING
    FsxNetAppConsumerDTO:
      type: object
      description: This is a definition of FSx-NetApp(s) available for Provisioning DB services in Tessell.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          description: The name of the FSx NetApp
        vpc:
          type: string
          description: The name of the vpc
        subscription:
          type: string
          description: The name of the subscription
          minLength: 1
          maxLength: 128
        configurations:
          $ref: '#/components/schemas/FsxNetAppConfigurationInfo'
        infrastructureInfo:
          $ref: '#/components/schemas/FsxNetAppInfrastructureInfo'
        connectivityInfo:
          $ref: '#/components/schemas/FsxNetAppConnectivityInfo'
        svmInfo:
          type: array
          items:
            $ref: '#/components/schemas/FsxNetAppSvmConsumerDTO'
        status:
          $ref: '#/components/schemas/FsxNetAppStatus'
        dateCreated:
          type: string
          description: Timestamp when the entity was created
          format: date-time
    FsxNetAppConfigurationInfoOps:
      type: object
      description: This is the configuration of FSx NetApp File System
      properties:
        throughput:
          description: Throughput in MB per second
          type: integer
          format: int32
          minimum: 0
          default: 0
        iops:
          description: operations per second
          type: integer
          format: int64
          minimum: 0
          default: 0
        maxStorage:
          description: Max storage in bytes
          type: integer
          format: int64
          minimum: 0
          default: 0
        usedStorage:
          description: Used storage in bytes
          type: integer
          format: int64
          minimum: 0
          default: 0
    FsxNetAppSvmConnectivityInfo:
      type: object
      description: This is a definition for Tessell FSx-NetApp SVM connectivity
      properties:
        endpoints:
          description: FSx NetApp SVM endpoints
          type: object
          properties:
            iscsi:
              $ref: '#/components/schemas/FsxNetAppEndpointInfo'
            management:
              $ref: '#/components/schemas/FsxNetAppEndpointInfo'
            nfs:
              $ref: '#/components/schemas/FsxNetAppEndpointInfo'
            sbm:
              $ref: '#/components/schemas/FsxNetAppEndpointInfo'
    cloudType:
      description: Tessell supported cloud types
      type: string
      enum:
      - AWS
      - AZURE
      - GCP
      - OCI
    FsxNetAppEndpointInfo:
      type: object
      properties:
        dns:
          type: string
          description: The dns name of entity
        ipAddresses:
          type: array
          description: The ip address of the entity
          items:
            type: string
            format: ip4
    apiMetadata:
      title: apiMetadata
      type: object
      properties:
        timeZone:
          type: string
        records:
          type: integer
          format: int32
        pagination:
          $ref: '#/components/schemas/apiPaginationInfo'
    FsxNetAppSubnetInfo:
      type: object
      description: This is a definition for Tessell FSx subnet
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 128
          description: The name of the subnet
        availabilityZone:
          type: string
          description: az of the subnet
    FsxNetAppSvmConsumerDTO:
      type: object
      description: This is a definition of FSx-NetApp SVM(s) available for Provisioning DB services in Tessell.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 128
          description: The name of the FSx NetApp SVM
        status:
          $ref: '#/components/schemas/FsxNetAppSvmStatus'
        connectivityInfo:
          $ref: '#/components/schemas/FsxNetAppSvmConnectivityInfo'
        dateCreated:
          type: string
          description: Timestamp when the entity was created
          format: date-time
    FsxNetAppInfrastructureInfo:
      type: object
      description: This is definition for FSx NetApp's infrastructure info
      properties:
        deploymentType:
          $ref: '#/components/schemas/FsxNetAppDeploymentType'
        haPairs:
          type: integer
          format: int32
          maximum: 12
          minimum: 1
        availabilityZone:
          description: AZ of the FSx NetApp
          type: object
          properties:
            preferred:
              type: string
              description: Preferred az of the FSx NetApp
            standBy:
              type: string
              description: StandBy az of the FSx NetApp
        cloud:
          $ref: '#/components/schemas/cloudType'
        region:
          type: string
          description: Region of the FSx NetApp File System
        encryptionKey:
          description: Details of encryption key
          type: object
          properties:
            id:
              type: string
              description: Id of the encryption key
              format: uuid
            name:
              type: string
              description: name of the encryption key
    FsxNetAppDeploymentType:
      type: string
      enum:
      - Single-AZ 1
      - Single-AZ 2
      - Multi-AZ 1
      - Multi-AZ 2
      x-enum-varnames:
      - SINGLE_AZ_1
      - SINGLE_AZ_2
      - MULTI_AZ_1
      - MULTI_AZ_2
  parameters:
    pageOffset:
      name: page-offset
      in: query
      description: Page offset for get query
      required: false
      schema:
        type: integer
        format: int32
        default: 0
    fsx-statuses:
      name: statuses
      description: Statuses of FSx file system to be included
      in: query
      required: false
      schema:
        type: array
        items:
          $ref: '#/components/schemas/FsxNetAppStatus'
    subscription-query:
      name: subscription
      description: Filter the entities based on cloud-subscription
      in: query
      required: false
      schema:
        type: string
    fsx-skip-statuses:
      name: skip-statuses
      description: Statuses of FSx file system to be skipped
      in: query
      required: false
      schema:
        type: array
        items:
          $ref: '#/components/schemas/FsxNetAppStatus'
    pageSize:
      name: page-size
      in: query
      description: Page size for get query
      required: false
      schema:
        type: integer
        format: int32
        default: 10
    region-query:
      name: region
      description: Filter the entities based on cloud-region
      in: query
      required: false
      schema:
        type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
